#!/usr/bin/env python3

import sys


# call with nc
# echo "set active" | nc 127.0.0.1 8081
# echo "set inactive" | nc 127.0.0.1 8081
# echo "get status" | nc 127.0.0.1 8081

statusFile = '/home/baby-care/baby-care/surveillance-status'

while True:
  data = sys.stdin.readline().strip()
  
  if data == 'set active':
    with open(statusFile, 'w') as f:
      f.write('active')   
    print('activated')
  elif data == 'set inactive':
    with open(statusFile, 'w') as f:
      f.write('inactive')
    print('deactivated')
  elif data == 'get status':
    with open(statusFile, 'r') as f:
      print(f.read().strip())
  else:
    print('ignored')    

  sys.stdout.flush()
  break;